---

- name: import escapace.aws_cli role
  ansible.builtin.import_role:
    name: escapace.aws_cli

- name: copy run-cloudflared script
  ansible.builtin.copy:
    src: files/run-cloudflared
    dest: "/opt/cloudflared/bin/run-cloudflared"
    mode: 0750
    owner: cloudflared
    group: cloudflared
  tags:
    - run-cloudflared
