---
- name: copy run-cloudflared script
  ansible.builtin.copy:
    src: run-cloudflared
    dest: /opt/cloudflared/bin/run-cloudflared
    mode: "0750"
    owner: cloudflared
    group: cloudflared
  tags:
    - run-cloudflared
